runtime: java
env: flex
service: jdaprd

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always  # Require HTTPS

runtime_config:
  jdk: openjdk8
  server: jetty9

resources:
  memory_gb: 2.0
  

